name: jaffle_shop

version: '1.0.0'

config-version: 2

profile: jaffle_shop

model-paths: ["models"]

models:
  jaffle_shop:
    staging:
      +materialized: table

    marts:
      +materialized: table